### ISSUE TITLE
Shaders with preprocessing directives are incorrectly minified

### ISSUE THREAD

**Issue by djw** [mikecao/gulp-glsl#1]
New lines are significant when using preprocessing directives, so replacing them with empty strings results in a syntax error.

e.g.

```
#ifdef MAGIC
const float magicValue = 4.2;
#endif
```

`glsl-man` handles this correctly, but `gulp-glsl` overrides the newline character to be the empty string:

https://github.com/mikecao/gulp-glsl/blob/master/index.js#L31

**Comment by mikecao** [comment]
I think the problem is with the glsl-man string function. I've submitted an issue here:

https://github.com/lammas/glsl-man/issues/9

**Comment by djw** [comment]
Great, thanks, that's been fixed!
