### ISSUE TITLE
Invalid minifying

### ISSUE THREAD

**Issue by ducklord** [mikecao/gulp-glsl#2]
Hey

Found a small bug, gulp-glsl minfied this:
```
dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));
```
to this:
```
dir.x=-(lumaNW+lumaNE)-(lumaSW+lumaSE);
```
Which is not the same.

**Comment by ducklord** [comment]
It was run with options: `{format: 'raw', ext: function(ext) { return ext; }}`

**Comment by mikecao** [comment]
You can track the progress of the fix here https://github.com/lammas/glsl-man/issues/19.

As a workaround, you can do this:
```
dir.x = -1 * ((lumaNW + lumaNE) - (lumaSW + lumaSE));
```
And it should minify correctly.
